{% set name = "cylc-rose" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b2abd6c2202dca30f8912f71ab399592c3bf0633fb812f6fefe5b10e31cfa48e

build:
  number: 0
  skip: true  # [py<37 or not unix]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - metomi-rose-base ==2.0b3
    - cylc-flow-base ==8.0b3

test:
  imports:
    - cylc.flow
    - cylc.rose
    - metomi.rose
  commands:
    - PAGER=cat rose stem --help

about:
  home: https://github.com/cylc/cylc-rose
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: Cylc Rose is the bridge between Rose suite configurations and Cylc workflows.
  description: |
    Cylc Rose is a replacement for the rose suite-run command (present in Rose
    versions 2019.01 and earlier). It reads the rose-suite.conf file and
    performs the required actions.
  doc_url: https://cylc.github.io/cylc-doc/latest/html/plugins/cylc-rose.html
  dev_url: https://github.com/cylc/cylc-rose

extra:
  recipe-maintainers:
    - oliver-sanders
    - wxtim
    - metronnie
